apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacedfalse.farius.com
spec:
  group: farius.com
  scope: Cluster
  names:
    plural: namespacedfalse
    singular: namespacedfalses
    kind: namespacedfalse
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Define your spec properties here
                foo:
                  type: string
                bar:
                  type: integer
          required:
            - spec
