apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacedtrue.farius.com
spec:
  group: farius.com
  scope: Namespaced
  names:
    plural: namespacedtrue
    singular: namespacedtrues
    kind: namespacedtrue
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # Define your spec properties here
                foo:
                  type: string
                bar:
                  type: integer
          required:
            - spec
